/**
 * 
 */
var bandsSpecifications = {
    'mapbiomas-brazil': [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "int32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "int32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "int32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "int32"],
        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "int32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "int32"],
        ["ndvi_median_dry", "uint16"],
        ["ndvi_median_wet", "uint16"],
        ["ndvi_median", "uint16"],
        ["ndvi_amp", "uint16"],
        ["ndvi_stdDev", "int32"],
        ["ndwi_median", "uint16"],
        ["ndwi_median_dry", "uint16"],
        ["ndwi_median_wet", "uint16"],
        ["ndwi_amp", "uint16"],
        ["ndwi_stdDev", "int32"],
        ["evi2_median", "uint16"],
        ["evi2_median_dry", "uint16"],
        ["evi2_median_wet", "uint16"],
        ["evi2_amp", "uint16"],
        ["evi2_stdDev", "int32"],
        ["savi_median_dry", "uint16"],
        ["savi_median_wet", "uint16"],
        ["savi_median", "uint16"],
        ["savi_stdDev", "int32"],
        ["pri_median_dry", "uint16"],
        ["pri_median", "uint16"],
        ["pri_median_wet", "uint16"],
        ["gcvi_median", "uint16"],
        ["gcvi_median_dry", "uint16"],
        ["gcvi_median_wet", "uint16"],
        ["gcvi_stdDev", "int32"],
        ["hallcover_median", "uint16"],
        ["hallcover_stdDev", "int32"],
        ["cai_median", "uint16"],
        ["cai_median_dry", "uint16"],
        ["cai_stdDev", "int32"],
        ["gv_median", "uint8"],
        ["gv_amp", "uint8"],
        ["gv_stdDev", "int32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_stdDev", "int32"],
        ["npv_median", "uint8"],
        ["soil_median", "uint8"],
        ["soil_amp", "uint8"],
        ["soil_stdDev", "int32"],
        ["cloud_median", "uint8"],
        ["cloud_stdDev", "int32"],
        ["shade_median", "uint8"],
        ["shade_stdDev", "int32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "int32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "int32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        ["wefi_amp", "uint8"],
        ["wefi_stdDev", "int32"],
        // ["fns_median", "uint8"],
        // ["fns_median_dry", "uint8"],
        // ["fns_stdDev", "int32"],
        ["slope", "int16"]
    ],

    'mapbiomas-indonesia': [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "uint32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "uint32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "uint32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "uint32"],
        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "uint32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "uint32"],
        ["ndvi_median_dry", "uint8"],
        ["ndvi_median_wet", "uint8"],
        ["ndvi_median", "uint8"],
        ["ndvi_amp", "uint8"],
        ["ndvi_stdDev", "uint32"],
        ["ndwi_median", "uint8"],
        ["ndwi_median_dry", "uint8"],
        ["ndwi_median_wet", "uint8"],
        ["ndwi_amp", "uint8"],
        ["ndwi_stdDev", "uint32"],
        ["evi2_median", "uint8"],
        ["evi2_median_dry", "uint8"],
        ["evi2_median_wet", "uint8"],
        ["evi2_amp", "uint8"],
        ["evi2_stdDev", "uint32"],
        ["savi_median_dry", "uint8"],
        ["savi_median_wet", "uint8"],
        ["savi_median", "uint8"],
        ["savi_stdDev", "uint32"],
        ["pri_median_dry", "uint8"],
        ["pri_median", "uint8"],
        ["pri_median_wet", "uint8"],
        ["gcvi_median", "uint8"],
        ["gcvi_median_dry", "uint8"],
        ["gcvi_median_wet", "uint8"],
        ["gcvi_stdDev", "uint32"],
        ["hallcover_median", "uint16"],
        ["hallcover_stdDev", "uint32"],
        ["cai_median", "uint8"],
        ["cai_median_dry", "uint8"],
        ["cai_stdDev", "uint32"],
        ["gv_median", "uint8"],
        ["gv_amp", "uint8"],
        ["gv_stdDev", "uint32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_stdDev", "uint32"],
        ["npv_median", "uint8"],
        ["soil_median", "uint8"],
        ["soil_amp", "uint8"],
        ["soil_stdDev", "uint32"],
        ["cloud_median", "uint8"],
        ["cloud_stdDev", "uint32"],
        ["shade_median", "uint8"],
        ["shade_stdDev", "uint32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "uint32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "uint32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        ["wefi_amp", "uint8"],
        ["wefi_stdDev", "uint32"],
        ["fns_median", "uint8"],
        ["fns_median_dry", "uint8"],
        ["fns_stdDev", "uint32"],
        ["slope", "int16"],
    ],

    'mapbiomas-af-trinacional': [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "uint32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "uint32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "uint32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "uint32"],
        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "uint32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "uint32"],
        ["ndvi_median_dry", "uint8"],
        ["ndvi_median_wet", "uint8"],
        ["ndvi_median", "uint8"],
        ["ndvi_amp", "uint8"],
        ["ndvi_stdDev", "uint32"],
        ["ndwi_median", "uint8"],
        ["ndwi_median_dry", "uint8"],
        ["ndwi_median_wet", "uint8"],
        ["ndwi_amp", "uint8"],
        // ["ndwi_stdDev", "uint32"],
        ["evi2_median", "uint8"],
        ["evi2_median_dry", "uint8"],
        ["evi2_median_wet", "uint8"],
        ["evi2_amp", "uint8"],
        ["evi2_stdDev", "uint32"],
        ["savi_median_dry", "uint8"],
        ["savi_median_wet", "uint8"],
        ["savi_median", "uint8"],
        // ["savi_stdDev", "uint32"],
        ["pri_median_dry", "uint8"],
        ["pri_median", "uint8"],
        // ["pri_median_wet", "uint8"],
        ["gcvi_median", "uint8"],
        ["gcvi_median_dry", "uint8"],
        ["gcvi_median_wet", "uint8"],
        ["gcvi_stdDev", "uint32"],
        ["hallcover_median", "uint16"],
        // ["hallcover_stdDev", "uint32"],
        ["cai_median", "uint8"],
        // ["cai_median_dry", "uint8"],
        // ["cai_stdDev", "uint32"],
        ["gv_median", "uint8"],
        // ["gv_amp", "uint8"],
        ["gv_stdDev", "uint32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_stdDev", "uint32"],
        ["npv_median", "uint8"],
        ["soil_median", "uint8"],
        ["soil_amp", "uint8"],
        // ["soil_stdDev", "uint32"],
        ["cloud_median", "uint8"],
        // ["cloud_stdDev", "uint32"],
        ["shade_median", "uint8"],
        // ["shade_stdDev", "uint32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "uint32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "uint32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        // ["wefi_amp", "uint8"],
        ["wefi_stdDev", "uint32"],
        ["fns_median", "uint8"],
        ["fns_median_dry", "uint8"],
        ["fns_stdDev", "uint32"],
        ["slope", "int16"],
    ],

    'mapbiomas-pampa-trinacional': [
        ["blue_median", "uint16"],
        ["blue_median_wet", "uint16"],
        ["blue_median_dry", "uint16"],
        ["blue_min", "uint16"],
        ["blue_stdDev", "uint32"],
        ["green_median", "uint16"],
        ["green_median_dry", "uint16"],
        ["green_median_wet", "uint16"],
        ["green_median_texture", "int16"],
        ["green_min", "uint16"],
        ["green_stdDev", "uint32"],
        ["red_median", "uint16"],
        ["red_median_dry", "uint16"],
        ["red_min", "uint16"],
        ["red_median_wet", "uint16"],
        ["red_stdDev", "uint32"],
        ["nir_median", "uint16"],
        ["nir_median_dry", "uint16"],
        ["nir_median_wet", "uint16"],
        ["nir_min", "uint16"],
        ["nir_stdDev", "uint32"],
        ["swir1_median", "uint16"],
        ["swir1_median_dry", "uint16"],
        ["swir1_median_wet", "uint16"],
        ["swir1_min", "uint16"],
        ["swir1_stdDev", "uint32"],
        ["swir2_median", "uint16"],
        ["swir2_median_wet", "uint16"],
        ["swir2_median_dry", "uint16"],
        ["swir2_min", "uint16"],
        ["swir2_stdDev", "uint32"],
        ["ndvi_median_dry", "uint8"],
        ["ndvi_median_wet", "uint8"],
        ["ndvi_median", "uint8"],
        ["ndvi_amp", "uint8"],
        ["ndvi_stdDev", "uint32"],
        ["ndwi_median", "uint8"],
        ["ndwi_median_dry", "uint8"],
        ["ndwi_median_wet", "uint8"],
        ["ndwi_amp", "uint8"],
        // ["ndwi_stdDev", "uint32"],
        ["evi2_median", "uint8"],
        ["evi2_median_dry", "uint8"],
        ["evi2_median_wet", "uint8"],
        ["evi2_amp", "uint8"],
        ["evi2_stdDev", "uint32"],
        ["savi_median_dry", "uint8"],
        ["savi_median_wet", "uint8"],
        ["savi_median", "uint8"],
        // ["savi_stdDev", "uint32"],
        ["pri_median_dry", "uint8"],
        ["pri_median", "uint8"],
        // ["pri_median_wet", "uint8"],
        ["gcvi_median", "uint8"],
        ["gcvi_median_dry", "uint8"],
        ["gcvi_median_wet", "uint8"],
        ["gcvi_stdDev", "uint32"],
        ["hallcover_median", "uint16"],
        // ["hallcover_stdDev", "uint32"],
        ["cai_median", "uint8"],
        // ["cai_median_dry", "uint8"],
        // ["cai_stdDev", "uint32"],
        ["gv_median", "uint8"],
        // ["gv_amp", "uint8"],
        ["gv_stdDev", "uint32"],
        ["gvs_median", "uint8"],
        ["gvs_median_dry", "uint8"],
        ["gvs_median_wet", "uint8"],
        ["gvs_stdDev", "uint32"],
        ["npv_median", "uint8"],
        ["soil_median", "uint8"],
        ["soil_amp", "uint8"],
        // ["soil_stdDev", "uint32"],
        ["cloud_median", "uint8"],
        // ["cloud_stdDev", "uint32"],
        ["shade_median", "uint8"],
        // ["shade_stdDev", "uint32"],
        ["ndfi_median", "uint8"],
        ["ndfi_median_dry", "uint8"],
        ["ndfi_median_wet", "uint8"],
        ["ndfi_amp", "uint8"],
        ["ndfi_stdDev", "uint32"],
        ["sefi_median", "uint8"],
        ["sefi_stdDev", "uint32"],
        ["sefi_median_dry", "uint8"],
        ["wefi_median", "uint8"],
        ["wefi_median_wet", "uint8"],
        // ["wefi_amp", "uint8"],
        ["wefi_stdDev", "uint32"],
        ["fns_median", "uint8"],
        ["fns_median_dry", "uint8"],
        ["fns_stdDev", "uint32"],
        ["slope", "int16"],
    ],
};

/**
 * 
 */
var conversionFunctions = {

    "uint8": function (image) {
        return image.toUint8();
    },

    "uint16": function (image) {
        return image.toUint16();
    },

    "uint32": function (image) {
        return image.toUint32();
    },

    "int16": function (image) {
        return image.toInt16();
    },

};

/**
 * 
 * @param {*} image 
 */
exports.setBandTypes = function (image, projectName) {


    var imageSpecifBands = bandsSpecifications[projectName]
        .reduce(
            function (imageSpecifBands, bandSpecification) {

                var fun = conversionFunctions[bandSpecification[1]];

                return imageSpecifBands.addBands(
                    fun(image.select([bandSpecification[0]])),
                    [bandSpecification[0]],
                    true
                );
            }, ee.Image().select()
        );

    return ee.Image(imageSpecifBands.copyProperties(image));
};